services:
  postgres:
    container_name: postgres-trading
    image: postgres
    environment:
      POSTGRES_USER: chiheb
      POSTGRES_PASSWORD: chiheb
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: trading_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local

