spring:
  application:
    name: trading-investment-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: chiheb
    password: chiheb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine

caching:
  cache-spec: maximumSize=1000,expireAfterWrite=5m

alphavantage:
  api-key: NG9QRVNFCH4YYJDX
  base-url: https://www.alphavantage.co/query

logging:
  level:
    com.pi.trading_investment_backend.service.MarketDataService: INFO

