spring:
  application:
    name: trading-investment-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: chiheb
    password: chiheb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
